version: "3.9"

services:

  backend:
    build: ./backend
    container_name: django-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - ollama
      - ai-service
    environment:
      - OLLAMA_URL=http://ollama:11434
    networks:
      - rh-net


  ai-service:
    build: ./ai-service
    container_name: ai-service
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434
    networks:
      - rh-net


  # Servidor Ollama
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - rh-net


  # ServiÃ§o que baixa o modelo automaticamente
  ollama-init:
    image: ollama/ollama:latest
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    entrypoint: >
      /bin/sh -c "
      echo 'â³ Aguardando Ollama iniciar...';
      until ollama list > /dev/null 2>&1; do
        sleep 2;
      done;
      echo 'ðŸ“¦ Baixando modelo llama3.2:3b...';
      ollama pull llama3.2:3b;
      echo 'âœ… Modelo baixado com sucesso!';
      "
    networks:
      - rh-net


volumes:
  ollama_data:


networks:
  rh-net:
    driver: bridge