version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: rh_api
    ports:
      - "8000:8000"
    env_file:
      - .env

  ia_service:
    build:
      context: .
      dockerfile: ia_service/Dockerfile
    container_name: rh_ia_service
    ports:
      - "8001:8001"
    env_file:
      - .env
